name: lldb step over fails

on:
  push:
  workflow_dispatch:

jobs:
  test-macos:
    name: Test ${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - arch: x86_64
            os: macos-15-intel
            targets: "X86"
          - arch: arm64
            os: macos-14
            targets: "AArch64"
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Dependencies
        run: brew install ninja cmake ccache

      - name: Setup ccache
        uses: actions/cache@v4
        with:
          path: /Users/runner/Library/Caches/ccache
          key: ${{ runner.os }}-${{ matrix.arch }}-ccache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.arch }}-ccache-

      - name: Configure
        run: |
          cmake -S llvm -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_ASSERTIONS=OFF \
            -DLLVM_ENABLE_PROJECTS="clang;lldb" \
            -DLLVM_ENABLE_RUNTIMES="compiler-rt;libcxx;libcxxabi" \
            -DLLVM_TARGETS_TO_BUILD="${{ matrix.targets }}" \
            -DLLVM_HOST_TRIPLE="${{ matrix.arch }}-apple-macosx" \
            -DLLVM_CCACHE_BUILD=ON \
            -DCCACHE_DIR=/Users/runner/Library/Caches/ccache

      - name: Build
        run: ninja -C build lldb debugserver clang FileCheck dsymutil lldb-dotest

      - name: Run Tests
        run: |
          if [ "${{ matrix.arch }}" == "arm64" ]; then
            ./build/bin/lldb-dotest -v lldb/test/API/functionalities/builtin-debugtrap
          else
            ./build/bin/lldb-dotest -v lldb/test/Shell/Expr/TestExprWithSideEffect.cpp
            ./build/bin/lldb-dotest -v lldb/test/Shell/Expr/TestExprWithSideEffectOnConvenienceVar.cpp
          fi