name: lldb step over fails

on:
  push:
  workflow_dispatch:

jobs:
  test-macos:
    name: Test ${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - arch: arm64
            os: macos-14
            targets: "AArch64"
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Dependencies
        run: |
          brew install ninja cmake swig
          python3 -m venv ~/lldb-venv
          ~/lldb-venv/bin/pip install packaging psutil

      - name: Restore build cache
        id: cache-build
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-${{ matrix.arch }}-build-${{ hashFiles('llvm/CMakeLists.txt', 'llvm/cmake/**', 'clang/CMakeLists.txt', 'lldb/CMakeLists.txt', 'compiler-rt/CMakeLists.txt', 'libcxx/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.arch }}-build-

      - name: Configure
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          source ~/lldb-venv/bin/activate
          cmake -S llvm -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_ASSERTIONS=OFF \
            -DLLVM_ENABLE_PROJECTS="clang;lldb" \
            -DLLVM_ENABLE_RUNTIMES="compiler-rt;libcxx;libcxxabi;libunwind" \
            -DLLVM_TARGETS_TO_BUILD="${{ matrix.targets }}" \
            -DLLVM_HOST_TRIPLE="${{ matrix.arch }}-apple-macosx" \

      - name: Build
        run: |
          source ~/lldb-venv/bin/activate
          ninja -C build lldb debugserver clang FileCheck dsymutil count not llvm-config

      - name: Run Tests
        run: |
          source ~/lldb-venv/bin/activate
          if [ "${{ matrix.arch }}" == "arm64" ]; then
            ./build/bin/llvm-lit -v lldb/test/Shell/Expr/TestExprWithSideEffect.cpp
            ./build/bin/llvm-lit -v lldb/test/Shell/Expr/TestExprWithSideEffectOnConvenienceVar.cpp
          else
            ./build/bin/lldb-dotest -v lldb/test/API/functionalities/builtin-debugtrap
          fi
